### ISSUE TITLE
[FEATURE] Add `Open in Gitpod` badge

### ISSUE THREAD

**Issue by vikasganiga05** [EddieHubCommunity/DailyTips#30]
### Description

Add the `Open in Gitpod` badge to open the project on [Gitpod](https://gitpod.io) with instructions on how to build and prepare the developer environment specifically for the project.

### Screenshots

![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)

#### Here is the markdown for the badge :point_down:
<br />

```markdown
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/EddieHubCommunity/DailyTips)
```

---

#### Here is the .gitpod.yml file :point_down: 
<br />

> `.gitpod.yml`

```yml
tasks:
  - name: npm
    init: npm install

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

```
